export { Header } from "./Header";
export { Footer } from "./Footer";
export { SectionHeader } from "./SectionHeader";
export { Hero } from "./Hero";
export { Player } from "./Player";
export { NavMobile } from "./NavMobile";
export { Nav } from "./Nav";
export { MenuBtn } from "./MenuBtn";
export { Socials } from "./Socials";
